name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 5. Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test --reporter=line

      # 6. Upload HTML report (optional)
      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
